### ISSUE TITLE
Windows x86 32bit build

### ISSUE THREAD

**Issue by tdpsk** [cloudradar-monitoring/cagent#266]
Is there a Windows 32bit build? We are still running a hand full of Windows Server 2008 32bit machines we would like to monitor

**Comment by thorstenkramm** [comment]
I'm very sorry but we have no plans to create and maintain builds for 32bit windows. We dropped them some time ago because they were time-consuming on one hand and we don't see a massive demand on the other hand.
A "hand full" is not a demand that would justify the costs. Compiling is free, but quality assurance not ;-)
The source code is there. Just compile on your own.
