### ISSUE TITLE
Top pkg questions

### ISSUE THREAD

**Issue by requilence** [cloudradar-monitoring/cagent#76]
@soupdiver I have some questions on the Linux top calculation approach
Currently, it works like this:
1) get the list of process (listing `/proc/` dir)
2) for each process, you query the CPU times
3) sleep 1 second
4) get the new CPU times
5) calculate the delta and percent
6) wait 1 second
7) repeat from 1)

Problems: 
- it queries procfs actively every 1 second. I didn't make detailed profiling, but it seems like adding additional 1-2% of CPU load on my system. And it doesn't seem to add any precision for calculations
- You can lose some spikes inside the 6) it's better to use non-blocking mode (https://github.com/shirou/gopsutil/blob/master/process/process.go#L170)

**Comment by soupdiver** [comment]
> it queries procfs actively every 1 second. I didn't make detailed profiling, but it seems like adding additional 1-2% of CPU load on my system

Sounds likely... calculating the process stats does consume CPU power. When running `htop` on my machine it takes around 0.5%.
 Not sure if this on itself is a problem, since the detailed monitoring is just active for some (short) amount of time.

> And it doesn't seem to add any precision for calculations

Have you done some tests to prove that claim or why does it seem to add no precision?

> You can lose some spikes inside the 6)

Why?

> it's better to use non-blocking mode 

Why is it better to use the non-blocking call? Then we have to do the `time.Sleep` inside our code. I'm not sure if this will change something? 🤔

**Comment by requilence** [comment]
> Have you done some tests to prove that claim or why does it seem to add no precision?

Under the hood, it reads CPU time from /proc/<id>/stat (measured in clock ticks), not the percentage. So if you read once in a minute you can get the same(or even more precise because you don't lose on rounding) results as reading the CPU times every second, calculating Percentage and found the average.

> Why?

It loose spikes because when you wait 1 second some process can consume the CPU heavily

> Why is it better to use the non-blocking call? Then we have to do the time.Sleep inside our code. I'm not sure if this will change something? 🤔

Because now you are doing both. Sleeping inside the gopsutil(https://github.com/shirou/gopsutil/blob/master/process/process.go#L170) and sleeping outside of it.

**Comment by requilence** [comment]
top/htop reads CPU times every 2 second to update the percentage in the UI frequently. In our case by default we need to provide results once in 120 seconds

**Comment by soupdiver** [comment]
> Because now you are doing both.

Agree, that might be a dev leftover 🤔 
One sleep should be enough .

> It loose spikes because when you wait 1 second some process can consume the CPU heavily

I don't think so. `sleep` doesn't mean the whole machine/CPU sleeps... just the process. If another process is consuming a lot of CPU this will be visible on the next iteration.
This probably not fully applies if we `sleep` two times.  With removing one of the sleeps, it should be ok?

> In our case by default we need to provide results once in 120 seconds

It's not about how often we have to _report_ something... If there is a process that is short-lived but takes a lot of CPU every time we won't see it if we only measure every 120 seconds or?
That's why I measure that often, to catch all possible processes. And even if this takes 1,2 or % of CPU I still think that's fine because we only measure for a couple of minutes. But I can also be wrong with this assumption.

So, should we `sleep` in our loop or use the `Percent` call with a timeout?

**Comment by requilence** [comment]
> If another process is consuming a lot of CPU this will be visible on the next iteration.
It will not be visible if you run outer `time.Sleep()` together with `Percent(duration>0)`

In the current implementation (you refetch the process list so the struct with prev lastCPUTimes is not preserved) you can only use the inner sleep ( `Percent(duration>0)`) and remove the outer.

> It's not about how often we have to report something... If there is a process that is short-lived but takes a lot of CPU every time we won't see it if we only measure every 120 seconds

You sort by the `Load`. So if process appears only for 2 seconds it will likely have `Load=0` when we call (`HighestNLoad(5)`). And will be cut-off the result set.

**Comment by soupdiver** [comment]
> You sort by the Load

yep, that was my first approach. Maybe this simple way is not the best.

I will remove the outer wait loop then

**Comment by soupdiver** [comment]
Actually, I think it's better to keep the outer loop.
Otherwise we have to add another sleep for the windows implementation because it does not need 1s to return the process info. I think that's why I had the outer sleep 🤔 

Suggestion: keep the outer sleep, remove the interval in `Percent()` call.
What ya think? @requilence

**Comment by requilence** [comment]
> Actually, I think it's better to keep the outer loop.

I also thought so at first glance, but this way you will need to store `Processes()` list into map and merge it in order to preserve previous struct with `lastCPUTimes`

**Comment by soupdiver** [comment]
ah true... ok, so we have to decide for one site.
Probably easier then to add a sleep to the windows implementation instead merge the `lastCPUTimes `

**Comment by requilence** [comment]
We can close this I think
